Query and update animals table
farouqdaif1/Vet-clinic pull request #2
Opened 2022-02-21 17:50 UTC by farouqdaif1

> * Added a column species of type string to **animals** table. Modified  `schema.sql` file.
> * Inserted the following data into the `data.sql`
>   
>   * Animal: His name is Charmander. He was born on Feb 8th, 2020, and currently weighs -11kg. He is not neutered and he has never tried to escape.
>   * Animal: Her name is Plantmon. She was born on Nov 15th, 2022, and currently weighs -5.7kg. She is neutered and she has tried to escape 2 times.
>   * Animal: His name is Squirtle. He was born on Apr 2nd, 1993, and currently weighs -12.13kg. He was not neutered and he has tried to 3 times.
>   * Animal: His name is Angemon. He was born on Jun 12th, 2005, and currently weighs -45kg. He is neutered and he has tried to escape once.
>   * Animal: His name is Boarmon. He was born on Jun 7th, 2005, and currently weighs 20.4kg. He is neutered and he has tried to escape 7 times.
>   * Animal: Her name is Blossom. She was born on Oct 13th, 1998, and currently weighs 17kg. She is neutered and she has tried to escape 3 times.
> * Created a `transaction.sql` file to insert all transactions
> * Inside a transaction updated the animals table by setting the species column to unspecified. Verified that change was made. Then roll back the change and verify that species columns went back to the state before transaction.
> * Inside a transaction:
>   
>   * Updated the animals table by setting the species column to **digimon** for all animals that have a name ending in **mon**.
>   * Updated the animals table by setting the species column to **pokemon** for all animals that don't have species already set.
>   * **Commit** the transaction.
>   * Verified that change was made and persists after commit.
> * Inside a transaction **delete** all records in the animals table, then roll back the transaction and verified after **rollback**
> * Inside a transaction:
>   
>   * Delete all animals born after Jan 1st, 2022.
>   * Create a savepoint for the transaction.
>   * Update all animals' weight to be their weight multiplied by -1.
>   * Rollback to the savepoint
>   * Update all animals' weights that are negative to be their weight multiplied by -1.
>   * Commit transaction
> * Wrote queries for the given questions and added the queries in the` queries.sql` file.

2022-02-21 18:16 UTC, mmsesay requested changes
Hi @farouqdaif1, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-21 18:16 UTC, mmsesay commented on transaction.sql
> +
- [ ] The entire content of this file should be inside the `queries.sql` file. Because they help to analyze your data. 
In addition, you can remove the `transaction.sql` file after copying your content. This project requires students to only have 3 SQL files in their project. A `data.sql`, `schema.sql` and `queries.sql`

2022-02-21 18:16 UTC, mmsesay commented on transaction.sql
> +ROLLBACK;
- [ ] You did well writing this transaction :+1:  I think it will be nice to verify that your changes did roll back.
 
Try adding: `SELECT species from animals;` after roll back to verify the change.

2022-02-21 18:16 UTC, mmsesay commented on transaction.sql
> +COMMIT;
- [ ]  I suggest you try to verify that your changes were committed.
 
Try adding: `SELECT species from animals;`

2022-02-21 18:16 UTC, mmsesay commented on queries.sql
> +SELECT species,ROUND( AVG(escape_attempts))FROM animals WHERE date_of_birth BETWEEN '1990-1-1' AND '2000-1-1' GROUP BY species;
- [ ] Good one. But let's assume an animal was given birth to months after the 1st day and 1st month of the year 2000. This query won't pick out those animals, right? In that case, I will suggest you end your check on the last day and the last month of the year 2000. 

See example: `2000-31-12`

2022-02-21 18:16 UTC, mmsesay commented on queries.sql
> +(1 row)
- [ ] I can see you place the output of a query that doesn't exist in the file. Let's try adding the query that returns the count of how many animals are there on the animals' table.

2022-02-22 09:20 UTC, farouqdaif1 commented on transaction.sql
> +COMMIT;
Thanks, I will fix it

2022-02-22 09:20 UTC, farouqdaif1 commented on transaction.sql
> +ROLLBACK;
Thanks, I will fix it

2022-02-22 09:20 UTC, farouqdaif1 commented on transaction.sql
> +
Thanks, I will fix it

2022-02-22 09:21 UTC, farouqdaif1 commented on queries.sql
> +(1 row)
Thanks, I will fix it

2022-02-22 09:28 UTC, rukundoeric approved these changes
Hi @farouqdaif1,

_Excellent job on this project. Keep it up 🎆_

_Congratulations! 🎉  on the splendid job 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_


Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

------
>As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-02-22 09:30 UTC, merged